name: SoundVitrine

services:
  app:
    restart: on-failure:1
    image: Amphaal/soundvitrine
    build: 
      context: ../app
      target: runtime-xdebug
    ports:
      - "80:80" # HTTP
    volumes:
     - ../_state:/app/_state:rw
    environment:
      MERCURE_PUBLISHER_JWT_KEY: "${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}"   # required
      MERCURE_SUBSCRIBER_JWT_KEY: "${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}" # required
      ALLOW_SSE_TESTING: "1" # dev-only
    develop:
      watch:
        - action: sync+restart
          path: ../app/Caddyfile
          target: /etc/frankenphp/Caddyfile
        - action: sync
          path: ../app/files
          target: /app/public
    extra_hosts:
      - host.docker.internal:host-gateway