name: SoundVitrine

services:
  # [Swoole HTTP + WebSocket]
  swoole-app:
    restart: on-failure:1
    image: Amphaal/soundvitrine # gives a name to the generated image
    build: ../app
    environment:
      # debug env specific
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 1
      #
      SOUNDVITRINE_EXPOSED_HOST: localhost
      SOUNDVITRINE_EXPOSED_SCHEME: http
      #
      PORT: 80
    ports:
      - "80:80"
    volumes:
      - ../_state:/var/www/_state:rw
    develop:
      watch:
        - action: sync+restart
          path: ../app/server.php
          target: /var/www/server.php
        - action: sync
          path: ../app/_src
          target: ../app/_src
        - action: sync
          path: ../app/public
          target: ../app/public