# version: "3.7"

services:
  # [Swoole]
  swoole:
    container_name: swoole
    hostname: swoole
    restart: on-failure:2
    build: ./custom_images/php
    environment:
      AUTORELOAD_PROGRAMS: "swoole"
      AUTORELOAD_ANY_FILES: 1
    networks:
    - web-fronts
    # user: "1001:1001" # same as user using FTP
    volumes:
      - ../_data:/var/www/_data:rw
      - ../app/_src:/var/www/_src:ro
      - ../app/public:/var/www/public:ro
      - ../app/server.php:/var/www/server.php:ro

  # [NGINX Proxy]
  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx:alpine
    restart: on-failure:2
    depends_on:
      - swoole
    networks:
      - web-fronts
    volumes:
      - ../_data:/usr/share/nginx/html/extra_soundvitrine/_data:rw
      - ../app/public:/usr/share/nginx/html/extra_soundvitrine/public:ro
      - type: bind
        source: ../app/public.nginx.conf
        target: /usr/share/nginx/html/extra_soundvitrine/public.nginx.conf
        read_only: true
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - ./conf.d:/etc/nginx/conf.d:ro
    # https://github.com/nginx-proxy/nginx-proxy/issues/133#issuecomment-754094932
    # allows right logging of IP and forwarding of X-Forwarded-For [Requester IP], for reverse-proxy scenarii
    # without "mode:host", requester IP resolves to inadequate IPs
    ports:
      - target: 80
        published: 80
        mode: host

#
networks:
  web-fronts:
