version: "3.7"

services:
  # [PHP-FPM]
  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    restart: on-failure:2
    build: ./custom_images/php
    user: "1001:1001" # same as user using FTP
    volumes:
      - ../_data:/usr/share/nginx/html/extra_soundvitrine/_data:rw
      - ../app:/usr/share/nginx/html/extra_soundvitrine/app:ro
      - ./php.ini-custom:/usr/local/etc/php/php.ini:ro
    networks:
      - web-fronts

  # [Websockets]
  sound-sentry:
    container_name: sound-sentry
    hostname: sound-sentry
    restart: on-failure:2
    environment:
      - NODE_ENV=development
    volumes:
      - ../_data:/srv/data:rw
      - ./SoundSentry/dist:/home/node/app/dist:ro # override source files so breakpoints will trigger
    command: "--inspect=0.0.0.0 app"
    build:
      context: https://github.com/Amphaal/SoundSentry.git#main
    ports:
      - "3000:3000"
      - "9229:9229" # debug port
    networks:
      - web-fronts

  # [Proxy]
  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    image: nginx:alpine
    restart: on-failure:2
    depends_on:
      - php-fpm
    networks:
      - web-fronts
    volumes:
      - ../_data:/usr/share/nginx/html/extra_soundvitrine/_data:rw
      - ../app:/usr/share/nginx/html/extra_soundvitrine/app:ro
      #
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - ./conf.d:/etc/nginx/conf.d:ro
    # https://github.com/nginx-proxy/nginx-proxy/issues/133#issuecomment-754094932
    # allows right logging of IP and forwarding of X-Forwarded-For [Requester IP], for reverse-proxy scenarii
    # without "mode:host", requester IP resolves to inadequate IPs
    ports:
      - target: 80
        published: 80
        mode: host

#
networks:
  web-fronts:
